WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREY = (127, 127, 127)

WINDOW_SIZE = WIN_WIDTH, WIN_HEIGHT = (640, 480)
DISPLAY_SIZE = WIDTH, HEIGHT = (160, 120)

NAME = 'PvZ'
FPS = 60
VERSION = '0.1-beta'

# GAME MENU
LABEL_NAME_POS = (WIN_WIDTH // 2, WIN_HEIGHT // 4)
LABEL_LEVEL_POS = (WIN_WIDTH // 4, WIN_HEIGHT // 3 * 2 - 32)
BUTTON_PLAY_POS = (WIN_WIDTH // 4, WIN_HEIGHT // 3 * 2)
BUTTON_DOCS_POS = (WIN_WIDTH // 2, WIN_HEIGHT // 3 * 2)
BUTTON_QUIT_POS = (WIN_WIDTH // 4 * 3, WIN_HEIGHT // 3 * 2)

# LEVEL SPAWN
LEVEL = {
    '1-1': {
        'point': 10,
        'zombie': 'normal'
    }
}
